"use client";

import { useEffect, useRef, useState } from "react";
import { SpecChart } from "@/components/charts";
import { Badge, Card, DataTable } from "@/components/ui";
import { getSuggestions, postAsk } from "@/lib/api";
import { messageForError } from "@/lib/errors";
import type { AnswerResult } from "@/lib/types";

interface Turn {
  id: number;
  question: string;
  result: AnswerResult | null;
  error?: string;
}

const STEPS = ["Interpret", "Select tool", "Compute", "Explain"];

const FALLBACK_SUGGESTIONS = [
  "Which carrier has the highest delay rate?",
  "Show delayed orders by week for the last 3 months",
  "Predict demand for CRAYON for the next 4 months",
];

// Matches the backend MAX_QUESTION_CHARS default; the server enforces it too.
const MAX_QUESTION = 1000;

export default function AskPage() {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState("");
  const [pending, setPending] = useState(false);
  const [suggestions, setSuggestions] = useState<string[]>(FALLBACK_SUGGESTIONS);
  const nextId = useRef(1);

  useEffect(() => {
    const ctrl = new AbortController();
    getSuggestions(ctrl.signal)
      .then((s) => s.length && setSuggestions(s))
      .catch(() => {});
    return () => ctrl.abort();
  }, []);

  const ask = (question: string) => {
    const q = question.trim();
    if (!q || pending) return;
    const id = nextId.current++;
    setTurns((t) => [...t, { id, question: q, result: null }]);
    setInput("");
    setPending(true);
    // POST /api/v1/ask — the backend interprets (Gemini or rules) then computes.
    postAsk(q)
      .then((result) => {
        setTurns((t) => t.map((x) => (x.id === id ? { ...x, result } : x)));
      })
      .catch((e: unknown) => {
        const msg = messageForError(e);
        setTurns((t) => t.map((x) => (x.id === id ? { ...x, error: msg } : x)));
      })
      .finally(() => setPending(false));
  };

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h1 className="text-lg font-semibold tracking-tight">Ask the data</h1>
        <p className="mt-0.5 text-xs text-[var(--muted)]">
          The model only chooses a tool and writes a query plan. Every number below is
          computed from the dataset, never generated by the model.
        </p>
      </div>

      <div className="flex flex-wrap gap-2">
        {suggestions.map((s) => (
          <button
            key={s}
            type="button"
            onClick={() => ask(s)}
            className="rounded-full border border-[var(--border)] px-3 py-1.5 text-xs text-[var(--text-secondary)] transition-colors hover:bg-[var(--hover)]"
          >
            {s}
          </button>
        ))}
      </div>

      {/* Sticky just below the app header so the input stays reachable while
          scrolling through answers. Negative margins let the backdrop span the
          full content width. */}
      <div className="sticky top-14 z-10 -mx-4 border-b border-[var(--border)] bg-[var(--page)]/95 px-4 py-3 backdrop-blur sm:-mx-6 sm:px-6">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            ask(input);
          }}
          className="card flex items-center gap-2 p-2"
        >
          <input
            value={input}
            onChange={(e) => setInput(e.target.value.slice(0, MAX_QUESTION))}
            maxLength={MAX_QUESTION}
            placeholder="e.g. Which carrier has the highest delay rate?"
            className="flex-1 bg-transparent px-3 py-2 text-sm outline-none placeholder:text-[var(--muted)]"
          />
          {input.length > MAX_QUESTION * 0.8 && (
            <span className="shrink-0 text-[11px] tabular-nums text-[var(--muted)]">
              {input.length}/{MAX_QUESTION}
            </span>
          )}
          <button
            type="submit"
            disabled={pending || !input.trim()}
            className="rounded-lg px-4 py-2 text-sm font-medium text-white disabled:opacity-40"
            style={{ background: "var(--series-1)" }}
          >
            {pending ? "Thinking…" : "Ask"}
          </button>
        </form>
      </div>

      {turns.length === 0 && (
        <Card title="How a question is answered" subtitle="AI orchestrates; it does not compute">
          <ol className="grid gap-3 sm:grid-cols-4">
            {STEPS.map((s, i) => (
              <li key={s} className="rounded-lg border border-[var(--border)] p-3">
                <p className="text-[11px] text-[var(--muted)]">Step {i + 1}</p>
                <p className="mt-1 text-sm font-medium">{s}</p>
                <p className="mt-1 text-xs text-[var(--text-secondary)]">
                  {
                    [
                      "Parse the question into metrics, dimensions and a time window.",
                      "Route to the analytics query tool or the forecasting tool.",
                      "Run a validated, parameterised query against Postgres.",
                      "Return the answer, chart and the plan that produced them.",
                    ][i]
                  }
                </p>
              </li>
            ))}
          </ol>
        </Card>
      )}

      <div className="flex flex-col gap-5">
        {turns.map((t) => (
          <TurnView key={t.id} turn={t} />
        ))}
      </div>
    </div>
  );
}

function TurnView({ turn }: { turn: Turn }) {
  const [showPlan, setShowPlan] = useState(false);
  const r = turn.result;

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <p className="max-w-[70ch] rounded-2xl rounded-br-sm bg-[var(--hover)] px-4 py-2 text-sm">
          {turn.question}
        </p>
      </div>

      {turn.error ? (
        <Card>
          <p className="text-sm font-medium text-[var(--status-critical)]">{turn.error}</p>
        </Card>
      ) : !r ? (
        <Card>
          <p className="text-sm text-[var(--muted)]">Interpreting the question…</p>
        </Card>
      ) : (
        <Card
          action={
            <div className="flex items-center gap-2">
              <Badge
                tone={
                  r.confidence === "high" ? "good" : r.confidence === "medium" ? "warning" : "critical"
                }
              >
                {r.confidence} confidence
              </Badge>
              <Badge>{r.plan.tool}</Badge>
            </div>
          }
        >
          <p className="max-w-[80ch] text-sm leading-relaxed">{r.answer}</p>

          {r.chart && (
            <div className="mt-5">
              <p className="mb-2 text-xs font-medium text-[var(--text-secondary)]">
                {r.chart.title}
              </p>
              <SpecChart spec={r.chart} />
            </div>
          )}

          <div className="mt-5 rounded-lg border border-[var(--border)] p-3">
            <button
              type="button"
              onClick={() => setShowPlan((v) => !v)}
              className="flex w-full items-center justify-between text-left"
            >
              <span className="text-xs font-medium text-[var(--text-secondary)]">
                Explainability — filters, metrics, query plan and source rows
              </span>
              <span className="text-xs text-[var(--series-1)]">
                {showPlan ? "Hide" : "Show"}
              </span>
            </button>

            {showPlan && (
              <div className="mt-3 flex flex-col gap-4">
                <div className="grid gap-3 sm:grid-cols-3">
                  <Facts label="Filters used" items={Object.entries(r.plan.filters).map(([k, v]) => `${k}: ${v}`)} />
                  <Facts label="Metrics" items={r.plan.metrics} />
                  <Facts
                    label="Dimensions"
                    items={r.plan.dimensions.length ? r.plan.dimensions : ["none (scalar result)"]}
                  />
                </div>

                {r.plan.notes?.length ? (
                  <div>
                    <p className="mb-1 text-[11px] font-medium text-[var(--text-secondary)]">
                      Assumptions
                    </p>
                    <ul className="list-disc pl-4 text-xs text-[var(--text-secondary)]">
                      {r.plan.notes.map((n) => (
                        <li key={n}>{n}</li>
                      ))}
                    </ul>
                  </div>
                ) : null}

                <div>
                  <p className="mb-1 text-[11px] font-medium text-[var(--text-secondary)]">
                    Structured query plan
                  </p>
                  <pre className="overflow-auto rounded-lg border border-[var(--border)] bg-[var(--page)] p-3 text-[11px] leading-relaxed">
                    {JSON.stringify(r.plan, null, 2)}
                  </pre>
                </div>

                {r.table && (
                  <div>
                    <p className="mb-1 text-[11px] font-medium text-[var(--text-secondary)]">
                      Underlying data
                    </p>
                    <DataTable columns={r.table.columns} rows={r.table.rows} maxHeight={240} />
                  </div>
                )}
              </div>
            )}
          </div>
        </Card>
      )}
    </div>
  );
}

function Facts({ label, items }: { label: string; items: string[] }) {
  return (
    <div>
      <p className="mb-1 text-[11px] font-medium text-[var(--text-secondary)]">{label}</p>
      <ul className="flex flex-col gap-1">
        {items.map((i) => (
          <li
            key={i}
            className="rounded-md border border-[var(--border)] px-2 py-1 text-[11px] text-[var(--text-primary)]"
          >
            {i}
          </li>
        ))}
      </ul>
    </div>
  );
}
